### ISSUE TITLE
Corrupted .xlsx file when using a MemoryStream

### ISSUE THREAD

**Issue by odinnou** [sveinungf/spreadcheetah#10]
Hi, first of all thank you for your library! 
Incredible performances!!

I'm working on a migration from ClosedXML to spreadcheetah integration for .xlsx export (too much memory consumption with ClosedXML).

But, I'm facing a problem. I successfully generate file but when I open it, I get an error prompt

<img width="827" alt="image" src="https://user-images.githubusercontent.com/3084655/204741000-79e5843e-61aa-44e4-a44d-abdd6ebc6c2c.png">

EN translation: "_Sorry ... we found a problem in the content of "export.xlsx", but we can try to recover the maximum content. If the source of this workbook is reliable, click yes._".

After clicking "yes", I get **all** my rows (no data loss).
I got this error with an empty file too.

Here my implementation:

```
    public async Task<byte[]> Execute(IEnumerable<PocDto> records)
    {
        await using MemoryStream memoryStream = new MemoryStream();
        await using Spreadsheet spreadsheet = await Spreadsheet.CreateNewAsync(memoryStream);

        await spreadsheet.StartWorksheetAsync("export");

        foreach (PocDto record in records)
        {
            await spreadsheet.AddAsRowAsync(record, PocDtoRowContext.Default.PocDto);
        }

        await spreadsheet.FinishAsync();

        byte[] bytes = new byte[(int)memoryStream.Length];
        memoryStream.Seek(0, SeekOrigin.Begin);
        memoryStream.Read(bytes, 0, (int)memoryStream.Length);

        return bytes;
    }
```

Called from a HTTP GET endpoint

```
    public async Task<FileContentResult> Export(some_inputs)
    {
        IEnumerable<PocDto> exportableDtos = ....;

        byte[] excelAsBytesArray = await _excelBuilder.Execute(exportableDtos);
        return File(excelAsBytesArray, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileDownloadName: $"export_{DateTime.Now:yyyyMMdd_hhmmssfff}.xlsx");
    }
```

After several hours, I try with a FileStream, I get a correct file, so it seems due to the usage of a **MemoryStream**.

Unfortunately, I working on docker image and usage of a FileStream is not an option.

Thanks in advance if you can help me!
Kind regards

Rémi.

**Comment by sveinungf** [comment]
Thanks for the feedback!
This kind of error can happen when the spreadsheet is not finalized. Can you try disposing the spreadsheet before copying to the byte array? For example with a using block:
```
await using (var spreadsheet = await Spreadsheet.CreateNewAsync(memoryStream))
{
    // ...

    await spreadsheet.FinishAsync();
}

byte[] bytes = new byte[(int)memoryStream.Length];
memoryStream.Seek(0, SeekOrigin.Begin);
memoryStream.Read(bytes, 0, (int)memoryStream.Length);
```

**Comment by odinnou** [comment]
That works! Thanks!!
