### ISSUE TITLE
Merge cells

### ISSUE THREAD

**Issue by bernardogeneroso** [sveinungf/spreadcheetah#13]
I didn't find anything to merge cells, can you help me?
Thank you!

**Comment by sveinungf** [comment]
It is not supported yet, but it will be one of the next features I will work on.

**Comment by bernardogeneroso** [comment]
Ok, nice to see, thank you!

**Comment by sveinungf** [comment]
Merging cells is now supported in version 1.9.0.

**Comment by sharpjoe** [comment]
Trying to roll over to spreadcheetah and having trouble with finding the Merge cells support: 

I saw the post that says it's in version 1.9 but can't find it in the source, and it doesn't seem to be mentioned in the release notes... did it get dropped along the way?
