### ISSUE TITLE
Add support for AutoFilter

### ISSUE THREAD

**Issue by mderubertis-velan** [sveinungf/spreadcheetah#14]
Please add support for AutoFilter for Worksheets.

In the sheet XML, there is a property name `autoFilter` that should be placed after `<sheetData/>`. 

Based on preliminary testing, it should contain two attributes:

- ref: The range of data (will be the entire range for my purposes, but will try to make it configurable)
- xr:uid: Unknown. Will need to look into the OpenXML specs to see if it's listed.

`<autoFilter ref="A1:P23171" xr:uid="{68C1B19E-3898-438A-AF56-CC838EB61945}"/>`

I will create a pull request once I have something worth testing.

**Comment by mderubertis-velan** [comment]
https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.autofilter?view=openxml-2.8.1 is a good reference for allowing custom column filtering

Also, looking into the same file that had that UID, it seems that the `<worksheet/>` property has the `xr:uid` property as well. We would need to add a worksheet GUID if auto filtering is enabled.

**Comment by mderubertis-velan** [comment]
Created PR #15 with the initial code setup.

By default, all worksheets have a `xr:uid` regardless if auto filtering is enabled.
Since auto filtering requires a range, `AutoFilterOptions` provides the range through `WorksheetOptions` so it is accessible when it comes time to write the `<autoFilter/>` element, without assuming that the user wants the entire sheet filtered and having to keep track of the column and row counts.

Let me know if I am on the right track.

**Comment by sveinungf** [comment]
This is now available in version 1.9.0.
