### ISSUE TITLE
image support

### ISSUE THREAD

**Issue by farukgocgun** [sveinungf/spreadcheetah#17]
I couldn't find anything about adding an image. How can I insert an image, especially an embedded one?

**Comment by sveinungf** [comment]
There is no support for this yet, but it's something I want to add support for in a future version. Can you tell me a bit about what you would use it for?

**Comment by farukgocgun** [comment]
let's assume to create an Excel report for employees that includes the app logo at the top and the employee's photo per row. 
Spreadcheetah seems a very quality library. Thus, It would be nice to write your roadmap in readme.

**Comment by sveinungf** [comment]
Support for PNG images are now available in v1.12.0. Support for other image formats can be added in the future.
