### ISSUE TITLE
Add hyperlink support

### ISSUE THREAD

**Issue by alexmurari** [sveinungf/spreadcheetah#18]
Hi,

First of all thanks for this project. I like the API simplicity for creating the spreasheet files.

I need to define hyperlinks, for example:

`new HyperlinkCell("https://github.com/sveinungf/spreadcheetah/", "spreadcheetah's Repository");`

where we have the URI and the display text.

Currently, the URI is displayed as plain text, wihtout hyperlink formatting.

![image](https://github.com/sveinungf/spreadcheetah/assets/11204378/dd16bb29-a29d-40ed-8a0d-dcd095616bbb)

I don't know if you have something that covers that scenario already, but I couldn't find it.

Thanks!

**Comment by sveinungf** [comment]
Thanks for the feedback!
This is not currently supported, but I'll add it in a future version.

**Comment by sveinungf** [comment]
An option could also be to use a `HYPERLINK` formula, which is supported. It won't get hyperlink formatting automatically, but you can use a style for that:

```
var urlStyle = new Style();
urlStyle.Font.Color = Color.FromArgb(5, 99, 193);
var urlStyleId = spreadsheet.AddStyle(urlStyle);

var uri = new Uri("https://github.com/sveinungf/spreadcheetah");
var displayText = "SpreadCheetah's Repository";
var formula = new Formula($"HYPERLINK(\"{uri.AbsoluteUri}\",\"{displayText}\")");
var cell = new Cell(formula, urlStyleId);
```
![image](https://github.com/sveinungf/spreadcheetah/assets/2733134/e2349657-e501-4883-8c47-480723c01bb4)

**Comment by alexmurari** [comment]
That's great. Works like a charm.

Well, it's up to you to close this issue if this will be the official approach to creating hyperlinks or leave it open if you'll work on a native approach to it.

**Comment by sveinungf** [comment]
Great! I'll close the issue for now. It can be reopened later if there would be a compelling reason for doing it differently.
