### ISSUE TITLE
Request: Would it be possible to sign the assembly with a strong name?

### ISSUE THREAD

**Issue by AlexVallat** [sveinungf/spreadcheetah#19]
In order to reference this assembly from another assembly which is signed, a strongly-named assembly is required. Could you add strong-name signing to this assembly? https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name

All it should take is generating a keyfile with sn.exe: https://learn.microsoft.com/en-us/dotnet/standard/assembly/create-public-private-key-pair and then checking the box in the project properties. I can provide a PR for this if you like (unless you want to keep the keyfile private so no fork can identify as being the same assembly).

**Comment by sveinungf** [comment]
Sure, I'll look into this for the next release. Thanks for offering to make a PR, but I'd rather keep the keyfile private for now.

**Comment by sveinungf** [comment]
The assembly is now being signed with a strong name, from version 1.11.0 going forwards.

**Comment by AlexVallat** [comment]
That's great, it's really helpful for me. Thanks.
