### ISSUE TITLE
Add columns title and order customisation attributes to source generator

### ISSUE THREAD

**Issue by ilivit** [sveinungf/spreadcheetah#21]
Could you add an option to specify the title of the column and it's order with the attributes?

This would be pretty useful when a property name doesn't represent what is expected in the column header (e.g. multiple words or non-latin name). The columns order attribute would allow storing the row model properties in an arbitrary order (e.g. sorted alphabetically).

I'd suggest using the `DataMemberAttribute` to specify an order and the `DescriptionAttribute` to specify a custom name.

```c#
[DataMember(Order = 1)]
[Description("Some value")]
public string SomeValue { get; set; }
```

**Comment by jonsagara** [comment]
This would be a very nice feature.

I love this library. Thanks for your hard work!

**Comment by sveinungf** [comment]
This is now supported in v1.13.0. Specifying the order between columns can be done with the new `ColumnOrder` attribute. The new `ColumnHeader` attribute can be used to set a column header, and a row of column headers can be added by calling `Spreadsheet.AddHeaderRowAsync`.
