### ISSUE TITLE
DateTime cell

### ISSUE THREAD

**Issue by fugaku** [sveinungf/spreadcheetah#3]
Hi,
Do you have any example for a DateTime cell with format ?

**Comment by sveinungf** [comment]
DateTime cells are not supported yet, but it is the next feature I will be working on. Once it is ready I will also create an example of how to use it with formats.

**Comment by sveinungf** [comment]
Version 1.6.0 introduces support for DateTime cells. An example of how to use it has been added to the list of examples on the main page.
