### ISSUE TITLE
Source generator - use fields of base class

### ISSUE THREAD

**Issue by Ashymonth** [sveinungf/spreadcheetah#49]
Currently, the source code generator generates properties only for the class that is specified in the worksheet row attribute but the properties of the base class are ignored. 

I can try to make a PR if you want

**Comment by sveinungf** [comment]
Sure! Contributions are welcome.

**Comment by Ashymonth** [comment]
What do you think about cases where a user puts an inherited property in the middle of other properties?
For Roslyn, it's still an inherited property, but the class doesn't actually have it.

Like in this example 
![image](https://github.com/sveinungf/spreadcheetah/assets/43273144/3f3d32b5-e4a3-4b4c-a491-320f4b0b817e)

Record has filed Name, Value, Age but for analyzer this is Name, Age, Value because Value is inherited

**Comment by sveinungf** [comment]
I think the expectation for the order would be base class properties first, and then derived class properties. So Value, Name, Age in this example. Otherwise the order could change if there was a change between using primary constructors or default constructors, which might catch users off guard.
