### ISSUE TITLE
Support ColumnIgnore Attribute, or add an overload to ColumnHeader to ignore fields from the output

### ISSUE THREAD

**Issue by cajuncoding** [sveinungf/spreadcheetah#76]
It's a very common use case to have Models that have additional fields that we don't wish to output such as what is provided by `JsonIgnore` attribute for Json. For the Spreadcheetah outputs we don't always want to spin up new models just to hide fields so a feature to support this would be very useful. It could be a new `[ColumnIgnore]` attribute or an overload on the existing `[ColumnHeader]` attribute. Along with some additional examples in the docs to show these additional features for the CodeGen functionality. 😁

**Comment by sveinungf** [comment]
Sounds like a useful feature. Thanks for the suggestion!

**Comment by sveinungf** [comment]
The `ColumnIgnore` attribute is now available in version 1.19.0. An example can be seen in the [wiki](https://github.com/sveinungf/spreadcheetah/wiki/Source-generator#ignoring-properties).
