### ISSUE TITLE
Cell format: Align

### ISSUE THREAD

**Issue by truemed** [sveinungf/spreadcheetah#8]
This is an excellent library to generate spreadsheets! Thank you.
Is there a way to format a cell with a simple text alignment?
Horizontal (left, center, right) and/or Vertical alignment (top, middle, bottom).

**Comment by sveinungf** [comment]
Thanks for the feedback!
Text alignments are not supported yet. It will be one of the next features I will work on.

**Comment by bernardogeneroso** [comment]
Hi, exist any date set to launch this feature?
I have same opinion of @truemed, excellent library!

**Comment by sveinungf** [comment]
Thanks! A new version will be released in a few days time. It will include support for text alignments.

**Comment by sveinungf** [comment]
Text alignments are now supported in version 1.8.0.
